apiVersion: 1

datasources:
  - name: InfluxDB_v2
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: soilmind
      defaultBucket: smartfarm
    secureJsonData:
      token: soilmind-token-123
